version: "3.9"

services:
  web:
    image: api_counts:2.0
    build: .
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
    ports:
      - "80:80"
  redis:
    image: redis:alpine